language: python
sudo: false
python:
  - 3.8.0
env:
  - FLASK_APP=app.py

before_install:
  - pip install poetry
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install: 
  - make install

script:
  - make lint
  - make test
