version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - "./:/app"
    ports:
      - 8080:8080
  # nginx:
  #   image: webapp-nginx
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-nginx
  #   ports:
  #     - 5000:80
  #   depends_on:
  #     - flask
