version: '3'

services:
  postgres:
    image: postgres:12
    ports:
      - 5444:5432
    volumes:
      - ./var/postgresql-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: junior
      POSTGRES_USER: junior
      POSTGRES_PASSWORD: junior
