"""empty message

Revision ID: 0124d69ded12
Revises: b9cceac46b75
Create Date: 2019-12-02 18:19:51.610055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0124d69ded12'
down_revision = 'b9cceac46b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_users_relations', sa.Column('set_like', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_users_relations', 'set_like')
    # ### end Alembic commands ###
