"""add github_id

Revision ID: 216128ca7f79
Revises: 6260d062e7b6
Create Date: 2019-11-22 17:26:16.863248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216128ca7f79'
down_revision = '6260d062e7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###
