"""empty message

Revision ID: 385007b560d3
Revises: 253297d1ec2a
Create Date: 2019-09-24 22:15:16.607055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385007b560d3'
down_revision = '253297d1ec2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'text')
    # ### end Alembic commands ###
