"""empty message

Revision ID: 3d23d2b6fb70
Revises: 0124d69ded12
Create Date: 2019-12-04 16:20:08.386678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d23d2b6fb70'
down_revision = '0124d69ded12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answers', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'owner_id')
    # ### end Alembic commands ###
