"""empty message

Revision ID: 508843369a49
Revises: 837a82783686
Create Date: 2019-11-22 09:57:24.153928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508843369a49'
down_revision = '837a82783686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_aproved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_aproved')
    # ### end Alembic commands ###
