"""empty message

Revision ID: 6260d062e7b6
Revises: 837a82783686
Create Date: 2019-11-21 11:18:53.124057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6260d062e7b6'
down_revision = 'df92146c1c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chapters', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chapters', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.drop_column('chapters', 'section_id')
    op.drop_table('sections')
    # ### end Alembic commands ###
