"""empty message

Revision ID: 818fb50521d3
Revises: dc88b8fdb2ac
Create Date: 2019-10-24 23:58:00.426247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818fb50521d3'
down_revision = 'dc88b8fdb2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_relations')
    # ### end Alembic commands ###
