"""empty message

Revision ID: 837a82783686
Revises: e11d4c5e8988
Create Date: 2019-10-30 22:15:06.510514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837a82783686'
down_revision = 'e11d4c5e8988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_answers', sa.Column('right', sa.Boolean(), nullable=False, server_default='FALSE'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_answers', 'right')
    # ### end Alembic commands ###
