"""add yandex_id

Revision ID: a85b791203a7
Revises: 3d23d2b6fb70
Create Date: 2019-12-10 13:51:07.611651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85b791203a7'
down_revision = '3d23d2b6fb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'yandex_id')
    # ### end Alembic commands ###
