"""empty message

Revision ID: b03ae470e8a6
Revises: 385007b560d3
Create Date: 2019-09-25 17:48:16.359528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03ae470e8a6'
down_revision = '385007b560d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_oauth', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_oauth')
    # ### end Alembic commands ###
