"""empty message

Revision ID: c7e984687a73
Revises: 79c8b1e6f21c
Create Date: 2019-11-29 15:37:34.953068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e984687a73'
down_revision = '79c8b1e6f21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
