"""empty message

Revision ID: f192865895e2
Revises: 216128ca7f79
Create Date: 2019-11-25 17:32:24.115451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f192865895e2'
down_revision = '216128ca7f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gravatar', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gravatar')
    # ### end Alembic commands ###
